### PR TITLE
Update argocd namespace to openshift-gitops

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**
> /kind enhancement

**What does this PR do / why we need it**:
The GitOps operator creates an argocd instance in `openshift-gitops` namespace. This PR updates argocd namespace to `openshift-gitops` and removes the default argocd instance which gets created during bootstrap

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by chetan-rns** [comment]
@amitkrout May need your help for updating the scripts to adopt this new change

**Comment by amitkrout** [comment]
> @amitkrout May need your help for updating the scripts to adopt this new change

Curently CI is passing because the e2e test script - https://github.com/redhat-developer/kam/blob/master/test/e2e/features/basic.feature has not gone that far to report the operator installation in the wrong namespace ```argocd```.

I fetched the pr and made changes accordingly in the operator and setup preparation script. ```make prepare-test-cluster``` reports failure while creating ```openshift-gitops``` namespace.
```
++ oc new-project openshift-gitops
Error from server (Forbidden): project.project.openshift.io "openshift-gitops" is forbidden: cannot request a project starting with "openshift-"
```

@chetan-rns Have you verified the day1 and day2 command manually with your changes ? if yes then @wtam2018 please review the pr and merge the pr after review comments are addressed. 

We will track and fix operator and setup preparation script failure in another pr.

**Comment by chetan-rns** [comment]
@amitkrout `openshift-gitops` namespace will be created by the operator. Maybe we just have to create the OLM resources like we do for pipelines operator in the script.

**Comment by chetan-rns** [comment]
I tested it with bootstrap and all the argocd applications have `openshift-gitops` namespace. The argocd instance file is no longer generated since it's created by the operator

**Pull request merged**
