### PR TITLE
Update secrets section in the docs

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

/kind documentation

**What does this PR do / why we need it**:
The cicd namespace is only created when the Argo CD apps are created. Move the instructions for applying secrets after the apps are created

**Have you updated the necessary documentation?**

* [x ] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by varshab1210** [comment]
Thanks for the pr @chetan-rns 
/lgtm

**Review by ishitasequeira — COMMENTED** [review]
@chetan-rns do we want to mention that this would not work if 2FA is on ?

**Review by ishitasequeira — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
