### PR TITLE
[WIP] Add note about private repo workaround

### PR DESCRIPTION
**Pull request by reginapizza**
**What type of PR is this?**
 /kind documentation

**What does this PR do / why we need it**:
Includes note about how to connect to a private git repo because currently there is some trouble doing so.

If necessary I can create and link to an actual doc in the repo but I figured that just linking to the docs in Argo CD was sufficient because they cover it very thoroughly.

### CODE REVIEW

**Comment by reginapizza** [comment]
Test aren't passing- I tried running `go mod tidy` and `make cmd-docs` but neither changed anything. Error says "go mod state is not clean"? Not sure what that means I need to do :/ 

@wtam2018 any ideas?

**Comment by varshab1210** [comment]
pr https://github.com/redhat-developer/kam/pull/198 has been merged into master. @reginapizza would you please rebase your pr

**Comment by chetan-rns** [comment]
@reginapizza @wtam2018 Given that updating the CR doesn't work, should we even mention the approach in kam docs? We could directly point to the Argo CD docs page that explains configuring private repositories with CLI/UI. WDYT?

**Comment by reginapizza** [comment]
@chetan-rns so you mean basically get rid of this whole section and just point to [the Argo CD docs](https://argoproj.github.io/argo-cd/user-guide/private-repositories/)? I'd be okay with that, my reasoning for not doing that is I wasn't sure if this would be getting fixed in the future and we would have to re-write it at some point.

**Comment by chetan-rns** [comment]
@reginapizza I've raised a PR to fix this. But I doubt it'll go with GitOps operator v1.1 https://github.com/argoproj-labs/argocd-operator/pull/269/files

**Comment by reginapizza** [comment]
@chetan-rns right, but in the meantime before that gets in shouldn't we be noting the workaround?

**Comment by ishitasequeira** [comment]
@reginapizza you could mention this work around for users who have their 2FA enabled

**Comment by reginapizza** [comment]
Just keeping this issue updated- 
This PR will not be needed if everything works as it's supposed to now that [PR #95 of the gitops operator](https://github.com/redhat-developer/gitops-operator/pull/95) is merged. Will retest and re-evaluate if the fix works and if this is still needed.

**Pull request closed without merging**
