### PR TITLE
Local bootstrapped environment up

### PR DESCRIPTION
**Pull request by varshab1210**
**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:

Adding test coverage to local.feature file.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

N/A

**How to test changes / Special notes to the reviewer**:

```
$ export SERVICE_REPO_URL=<Provide the URL for your Service repository>
$ export GITOPS_REPO_URL=<Provide the URL for your GitOps repository>
$ export IMAGE_REPO=<Image repository which is used to push newly built images>
$ export DOCKERCONFIGJSON_PATH=<Filepath to config.json which authenticates the image push to the desired image registry>
$ export GIT_ACCESS_TOKEN=<Used to authenticate repository clones, and commit-status notifications (if enabled)>
$ export PRIVATE_REPO_DRIVER=<If your Git repositories are on a custom domain, please indicate which driver to use github or gitlab>
$ make e2e-local
```

### CODE REVIEW

**Comment by varshab1210** [comment]
I added the bootstrapped environment locally in the local.feature file. But I am hitting the issue of ```error: failed to push some refs to 'https://github.com/varshab1210/gitops.git'```. @chetan-rns  can you please have a look. cc_ @amitkrout 

```
Log successfully started, logging into: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-results/integration_2021-4-5_11-37-37.log
Running integration test in: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Working directory set to: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Before suite
Feature: Basic test
  Checks whether KAM top-level commands behave correctly.
The bash instance has been started and will be used for testing.
Before feature

Feature: Local test
  This feature file captures local test automation.
  Due to certain technical challenges in OpenShiftCI test infra
  we are keeping test scenario in local feature file for verifying the bits locally.
  Once the CI challenges are fixed, we move these test under basic tag.
Before scenario

  Scenario: Execute KAM bootstrap command with default and --push-to-git=true flags                                                                                              # features/local.feature:8
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --push-to-git=true" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                  # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
2021/04/05 11:37:47 Successfully deleted repository: "https://github.com/varshab1210/gitops.git"
Before scenario

  Scenario: Execute KAM bootstrap command with default flags                                                                                                              # features/local.feature:12
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --overwrite" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                           # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
    And deleting directory "gitops" succeeds                                                                                                                              # fileops.go:37 -> github.com/code-ready/clicumber/testsuite.DeleteDirectory
    Then stderr should be empty                                                                                                                                           # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
2021/04/05 11:37:52 unable to delete repository: Not Found
Before scenario

  Scenario: Execute KAM bootstrap command with --output and --push-to-git=true flags                                                                                                                         # features/local.feature:18
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --push-to-git=true --output bootstrapresources" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                                              # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
2021/04/05 11:38:01 Successfully deleted repository: "https://github.com/varshab1210/gitops.git"
Before scenario

  Scenario: Execute KAM bootstrap command with default flags                                                                                                              # features/local.feature:22
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --overwrite" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                           # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
    And executing "cd gitops"                                                                                                                                             # shell.go:207 -> github.com/code-ready/clicumber/testsuite.ExecuteCommand
    And executing "git init ." succeeds                                                                                                                                   # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    And executing "git add ." succeeds                                                                                                                                    # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    And executing "git commit -m 'Initial commit.'" succeeds                                                                                                              # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    And executing "git remote add origin $GITOPS_REPO_URL" succeeds                                                                                                       # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    And executing "git push -u origin main" succeeds                                                                                                                      # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    command 'git push -u origin main', expected to succeed, exited with exit code: 1
Command stdout: 
Command stderr: error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/varshab1210/gitops.git'

    Then stderr should be empty                                                                                                                                           # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
2021/04/05 11:38:05 unable to delete repository: Not Found
After feature

Feature: Manual test
  This feature file captures only manual test steps.
  Due to certain technical challenges in OpenShiftCI test infra
  we are keeping few test scenario in manual feature file.
  Once the challenges are fixed, we automate these manual steps too.
After suite

--- Failed steps:

  Scenario: Execute KAM bootstrap command with default flags # features/local.feature:22
    And executing "git push -u origin main" succeeds # features/local.feature:30
      Error: command 'git push -u origin main', expected to succeed, exited with exit code: 1
Command stdout: 
Command stderr: error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/varshab1210/gitops.git'



4 scenarios (3 passed, 1 failed)
17 steps (15 passed, 1 failed, 1 skipped)
27.771881643s
FAIL    github.com/redhat-developer/kam/test/e2e        27.781s
FAIL
make: *** [Makefile:80: e2e-local] Error 1
```

**Comment by chetan-rns** [comment]
Hi @varshab1210, you're trying to push to a remote repository that doesn't exist. Here `git push` expects the repository to be already present

**Comment by amitkrout** [comment]
pr is not completed 
/hold

**Comment by varshab1210** [comment]
https://github.com/redhat-developer/kam/pull/220 has been fixed via https://github.com/redhat-developer/kam/pull/225
/close

**Pull request closed without merging**
