### PR TITLE
Update KAM Getting Started and Dev Console Documentation (#1032)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

**What type of PR is this?**

/kind documentation

**What does this PR do / why we need it**:
Update dev console docs to reflect 4.8 OpenShift Dev Console with 1.2 GitOps backend

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes Jira 1032

**How to test changes / Special notes to the reviewer**:
-

### CODE REVIEW

**Review by wtam2018 — COMMENTED** [review]
Do we still need step 6 and 7 to create a token secret?

**Comment by chetan-rns** [comment]
@wtam2018 Only the list page in OCP 4.8 supports getting the data from Application CR. We need the secrets until the feature is implemented for details page as well.

**Pull request merged**
