### PR TITLE
Fix CI repo delete race condition

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind bug
/kind failing-test

**What does this PR do / why we need it**:
https://github.com/redhat-developer/kam/pull/256#issuecomment-872319847

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes - CI race condition

**How to test changes / Special notes to the reviewer**:
Both the 4.7 and 4.8 CI jobs should pass

### CODE REVIEW

**Comment by amitkrout** [comment]
Copy pasted from CI logs

on 4.8 cluster
```
After scenario
2021/07/02 03:39:06 Successfully deleted repository: "https://github.com/*******/taxi-25748" 
```
on 4.7 cluster
```
After scenario
2021/07/02 03:39:39 Successfully deleted repository: "https://github.com/*******/taxi-25747" 
```

**Review by chetan-rns — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
