### PR TITLE
GITOPS-1000 Parse the image only if git repository is provided

### PR DESCRIPTION
**Pull request by ciiay**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind bug

**What does this PR do / why we need it**:
Added git repo url nil check for image parsing process.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #

**How to test changes / Special notes to the reviewer**:
`kam service add` command with no --git-repo-url flag is successful on OCP 4.8

### CODE REVIEW

**Comment by chetan-rns** [comment]
@ciiay Running `make gofmt` should fix the format

**Review by chetan-rns — CHANGES_REQUESTED** [review]
Thanks for the PR @ciiay. This will fix the issue. But after taking a closer look, kam is generating the webhook secret for the newly added service. I don't think the secret is being used anywhere since the service doesn't have a git repository. Should we consider adding a condition to avoid generating the webhook secret when the git repo is absent?

**Comment by varshab1210** [comment]
In pr https://github.com/redhat-developer/kam/pull/273 I am observing the below error

```
Command stderr:  ✗  failed to bootstrap resources: failed to read Docker config "/var/run/kam-data/kam-test-secrets/*******-kambot-auth.json" : open /var/run/kam-data/kam-test-secrets/*******-kambot-auth.json: no such file or directory
```
I am retesting this pr for cross verification

/test all

**Review by chetan-rns — APPROVED** [review]
Thanks, @ciiay!
 
/lgtm
/approve

**Pull request merged**
