### PR TITLE
updated README with devconsole 4.9 changes

### PR DESCRIPTION
**Pull request by reginapizza**
**What type of PR is this?**
 /kind documentation

**What does this PR do / why we need it**:
Updates descriptions and images with devconsole 4.9 changes

**Which issue(s) this PR fixes**:
This issue is from [GITOPS-1060](https://issues.redhat.com/browse/GITOPS-1060)

### CODE REVIEW

**Review by keithchong — APPROVED** [review]
/lgtm

**Review by chetan-rns — APPROVED** [review]
Thanks, @reginapizza!

/lgtm
/approve

**Pull request merged**
