### PR TITLE
KAM fails to push gitops configuration to GitLab (767)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

**What type of PR is this?**
 /kind bug

**What does this PR do / why we need it**:
KAM's `--push-to-git=true` flag does not work for GitLab repositories
The problem is in the go scm package.
See
https://github.com/jenkins-x/go-scm/pull/192

The fix is for us to pull in a version of the go package that has the fix.  The latest version is 1.6.6

The changes are as a result of performing these steps:
Update go.mod and change the go-scm version to 1.6.6
Run:
go mod tidy
go mod version
go mod vendor

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:
https://issues.redhat.com/browse/GITOPS-767

**How to test changes / Special notes to the reviewer**:
When using the KAM cli, specify `--push-to-git` in non-interactive mode, and specify a GitLab repo for your gitops repo

This might be risky for our 'version' since the dependencies changed, which can invalidate any recent testing that have been performed.

### CODE REVIEW

**Comment by chetan-rns** [comment]
@amitkrout Any idea why prow is failing for this PR? The log says it's failing to pull images.

**Comment by amitkrout** [comment]
> @amitkrout Any idea why prow is failing for this PR? The log says it's failing to pull images.

@chetan-rns Seems  registry ```registry.svc.ci.openshift.org``` is down. I have pinged platform team to have a look
```
$ docker pull registry.svc.ci.openshift.org/openshift/release:golang-1.14
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by chetan-rns** [comment]
Tested it locally and the GitLab repo is created successfully :)

**Comment by varshab1210** [comment]
I was verifying the change using the [local.feature](https://github.com/redhat-developer/kam/blob/master/test/e2e/features/local.feature) file by adding the scenario. Unfortunately it throws error due to my SSH key configuration 
```
Scenario: Execute KAM bootstrap command with gitlab host and --push-to-git=true flags
        When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GITHUB_TOKEN --push-to-git=true --overwrite --private-repo-driver gitlab" succeeds
        Then stderr should be empty
```

@keithchong Can you please add the test scenario in the local.feature file and run ```make e2e-local```

**Comment by chetan-rns** [comment]
@varshab1210 I faced the same SSH issue with GitLab. Configuring SSH keys is a prerequisite for Kam to push resources to GitHub/GitLab. It is mentioned in the docs 
```
An SSH key connected to your GitHub or GitLab account (here are the steps to create an SSH key for GitHub or GitLab)
```

**Review by chetan-rns — APPROVED** [review]
/lgtm

@wtam2018 Waiting for your approval since it updates the version of go-scm

**Comment by varshab1210** [comment]
> @varshab1210 I faced the same SSH issue with GitLab. Configuring SSH keys is a prerequisite for Kam to push resources to GitHub/GitLab. It is mentioned in the docs
> 
> ```
> An SSH key connected to your GitHub or GitLab account (here are the steps to create an SSH key for GitHub or GitLab)
> ```

Thanks @chetan-rns for the pointer. I have added my public SSH key in my GitLab account now it seems it works fine. I picked @amitkrout 's changes from the pr https://github.com/redhat-developer/kam/pull/210 and ran the e2e local test using the above mentioned scenario. To run my scenario successfully I commented the first two scenarios in the feature file. @amitkrout  I am sure you can also able to reproduce the failure so would you please take a look? Still I can see this below logs seems aftersuite function does not work properly

```
After suite
gh command is :  [gh alias set repo-delete api -X DELETE "repos/$1"]
gh command is :  [gh repo-delete varshab1210/gitops]
gh: Bad credentials (HTTP 401)
```

Test result for local test run

```
$ make e2e-local
Log successfully started, logging into: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-results/integration_2021-3-26_14-11-18.log
Running integration test in: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Working directory set to: /home/varshab/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Before suite
Feature: Basic test
  Checks whether KAM top-level commands behave correctly.
The bash instance has been started and will be used for testing.
Before feature

Feature: Local test
  This feature file captures local test automation.
  Due to certain technical challenges in OpenShiftCI test infra
  we are keeping test scenario in local feature file for verifying the bits locally.
  Once the CI challenges are fixed, we move these test under basic tag.

  Scenario: Execute KAM bootstrap command with gitlab host and --push-to-git=true flags                                                                                                                                             # features/local.feature:16
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GITHUB_TOKEN --push-to-git=true --overwrite --private-repo-driver $PRIVATE_REPO_DRIVER" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                                                                     # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
After feature
gh command is :  [gh alias set repo-delete api -X DELETE "repos/$1"]
gh command is :  [gh repo-delete varshab1210/gitops]
gh: Bad credentials (HTTP 401)


Feature: Manual test
  This feature file captures only manual test steps.
  Due to certain technical challenges in OpenShiftCI test infra
  we are keeping few test scenario in manual feature file.
  Once the challenges are fixed, we automate these manual steps too.
After suite
gh command is :  [gh alias set repo-delete api -X DELETE "repos/$1"]
gh command is :  [gh repo-delete varshab1210/gitops]
gh: Bad credentials (HTTP 401)


1 scenarios (1 passed)
2 steps (2 passed)
11.737875117s
ok      github.com/redhat-developer/kam/test/e2e        11.744s
```

**Comment by chetan-rns** [comment]
@varshab1210 @amitkrout The issue might be due to the usage of `gh` CLI. It's specific to GitHub and we can't use it with GitLab.

**Comment by amitkrout** [comment]
> @varshab1210 @amitkrout The issue might be due to the usage of `gh` CLI. It's specific to GitHub and we can't use it with GitLab.

Right. we can use - https://github.com/profclems/glab. I am looking into it.

**Comment by amitkrout** [comment]
> > @varshab1210 @amitkrout The issue might be due to the usage of `gh` CLI. It's specific to GitHub and we can't use it with GitLab.
> 
> Right. we can use - https://github.com/profclems/glab. I am looking into it.

It works
```
$ export GITLAB_TOKEN=*********

$ glab repo delete amit_rout/gitops -y
- Deleting project amit_rout/gitops
```
I will implement it in my pr #210

**Comment by amitkrout** [comment]
@varshab1210 I added your local scenario and merge kieth pr in my branch to test it. Here is the pass result
```
$ make e2e-local
Log successfully started, logging into: /Users/amit/go/src/github.com/redhat-developer/kam/test/e2e/out/test-results/integration_2021-3-26_18-32-33.log
Running integration test in: /Users/amit/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Working directory set to: /Users/amit/go/src/github.com/redhat-developer/kam/test/e2e/out/test-run
Before suite
Feature: Basic test
  Checks whether KAM top-level commands behave correctly.
The bash instance has been started and will be used for testing.
Before feature

Feature: Local test
  This feature file captures local test automation.
  Due to certain technical challenges in OpenShiftCI test infra
  we are keeping test scenario in local feature file for verifying the bits locally.
  Once the CI challenges are fixed, we move these test under basic tag.
Before scenario

  Scenario: Execute KAM bootstrap command with default and --push-to-git=true flags                                                                                              # features/local.feature:8
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --push-to-git=true" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                  # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
github command is :  [gh alias set repo-delete api -X DELETE "repos/$1"]
github command is :  [gh repo-delete amit_rout/gitops]
gh: Bad credentials (HTTP 401)

gitlab command is :  [glab repo delete amit_rout/gitops -y]
Before scenario

  Scenario: Execute KAM bootstrap command with default flags                                                                                                              # features/local.feature:12
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --overwrite" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                           # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
github command is :  [gh alias set repo-delete api -X DELETE "repos/$1"]
github command is :  [gh repo-delete amit_rout/gitops]
gh: Bad credentials (HTTP 401)

gitlab command is :  [glab repo delete amit_rout/gitops -y]
DELETE https://gitlab.com/api/v4/projects/amit_rout/gitops: 404 {message: 404 Project Not Found}

Before scenario

  Scenario: Execute KAM bootstrap command with gitlab host and --push-to-git=true flags                                                                                                                                  # features/local.feature:16
    When executing "kam bootstrap --service-repo-url $SERVICE_REPO_URL --gitops-repo-url $GITOPS_REPO_URL --git-host-access-token $GIT_ACCESS_TOKEN --push-to-git=true --output bootstrapresources --overwrite" succeeds # shell.go:234 -> github.com/code-ready/clicumber/testsuite.ExecuteCommandSucceedsOrFails
    Then stderr should be empty                                                                                                                                                                                          # shell.go:306 -> github.com/code-ready/clicumber/testsuite.CommandReturnShouldBeEmpty
github command is :  [gh alias set repo-delete api -X DELETE "repos/$1"]
github command is :  [gh repo-delete amit_rout/gitops]
gh: Bad credentials (HTTP 401)

gitlab command is :  [glab repo delete amit_rout/gitops -y]
After feature

Feature: Manual test
  This feature file captures only manual test steps.
  Due to certain technical challenges in OpenShiftCI test infra
  we are keeping few test scenario in manual feature file.
  Once the challenges are fixed, we automate these manual steps too.
After suite

3 scenarios (3 passed)
6 steps (6 passed)
31.80957498s
ok      github.com/redhat-developer/kam/test/e2e        32.856s
```
cc_ @chetan-rns

**Pull request merged**
