### PR TITLE
Update FAQ note for enterprise repo

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

> /kind documentation

**What does this PR do / why we need it**:
Update the FAQ section for disabling `sslVerify` in the enterprise repository
 
**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by amitkrout** [comment]
/approve

Ping @wtam2018

**Review by ishitasequeira — COMMENTED** [review]
/lgtm

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve

**Comment by amitkrout** [comment]
Timeout issue
/retest

**Pull request merged**
