### PR TITLE
[142] kam should trim leading and trailing spaces from input

### LINKED ISSUE #142: kam should trim leading and trailing spaces from input
**Describe the bug**
kam exits with error if the user provides answers with leading spaces in their response.  Trailing spaces can pose problems as well.

**To Reproduce**
1. Run kam bootstrap
2. When prompted to enter the URL for your GitOps repository, purposely add a space before your gitops URL
3. Hit enter

kam exits with an error

See output below:

```
kam bootstrap
  
Checking dependencies

 ✓  Checking if Sealed Secrets is installed with the default configuration [325ms]
 ✓  Checking if ArgoCD Operator is installed with the default configuration [721ms]
 ✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [846ms]
  
Starting interactive prompt

? Provide the URL for your GitOps repository  https://github.com/keithchong/gitops9.git
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1fadcb7]

goroutine 1 [running]:
github.com/redhat-developer/kam/pkg/cmd/ui.EnterGitRepo(0xc0002ed820, 0x2659cf6)
	/Users/kchong/wrh/git/kam/pkg/cmd/ui/ui.go:26 +0x117
github.com/redhat-developer/kam/pkg/cmd.initiateInteractiveMode(0xc00007fd50, 0xc0002ed820, 0x2874620, 0xc000495500)
	/Users/kchong/wrh/git/kam/pkg/cmd/bootstrap.go:161 +0x9d
github.com/redhat-developer/kam/pkg/cmd.(*BootstrapParameters).Complete(0xc00007fd50, 0x265fca6, 0x9, 0xc0004fe2c0, 0x34268e8, 0x0, 0x0, 0xc00018fc00, 0x2659e0a)
	/Users/kchong/wrh/git/kam/pkg/cmd/bootstrap.go:112 +0x14c
github.com/redhat-developer/kam/pkg/cmd/genericclioptions.GenericRun(0x2874660, 0xc00007fd50, 0xc0004fe2c0, 0x34268e8, 0x0, 0x0)
	/Users/kchong/wrh/git/kam/pkg/cmd/genericclioptions/runnable.go:23 +0x6e
github.com/redhat-developer/kam/pkg/cmd.NewCmdBootstrap.func1(0xc0004fe2c0, 0x34268e8, 0x0, 0x0)
	/Users/kchong/wrh/git/kam/pkg/cmd/bootstrap.go:324 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0004fe2c0, 0x34268e8, 0x0, 0x0, 0xc0004fe2c0, 0x34268e8)
	/Users/kchong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004fe000, 0x1008285, 0xc0000ae058, 0x0)
	/Users/kchong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kchong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/redhat-developer/kam/pkg/cmd.Execute()
	/Users/kchong/wrh/git/kam/pkg/cmd/kam.go:42 +0x2a
main.main()
	/Users/kchong/wrh/git/kam/cmd/kam/kam.go:8 +0x25

```

**Expected behavior**
kam should trim spaces. I discovered this problem when I copied and pasted the repo, and I inadvertantly copied a leading space.

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

**What type of PR is this?**

/kind bug

**What does this PR do / why we need it**:
Bad user experience if user inadvertantly adds leading and trailinig spaces to certain inputs.
Kam exits with error.

**Have you updated the necessary documentation?**
No doc update required.

**Which issue(s) this PR fixes**:

Fixes #142 

**How to test changes / Special notes to the reviewer**:
I tested this by adding leading and trailing spaces to all applicable prompts, except for secrets and the git access token

### CODE REVIEW

**Comment by keithchong** [comment]
Hi @bigkevmcd , please review.

**Review by bigkevmcd — CHANGES_REQUESTED** [review]
There are no tests for this change?

**Comment by keithchong** [comment]
Hi Kevin, I thought about https://issues.redhat.com/browse/GITOPS-514.  The only way the user can add spaces is in interactive mode. So I tested it manually. From the command line, the command framework already strips out the leading and trailing spaces. eg:

--flag test -flag2 value
--flag     test     --flag2    value

However, I'll see if I can test the changed methods in the UI package based on the existing headless tests.

**Comment by keithchong** [comment]
One pattern that we could potentially use is to handle the responses in a separate method

Current:
```
func EnterImageRepoExternalRepository() string {
	var imageRepoExt string
	prompt := &survey.Input{
		Message: "Image registry of the form....",
		Help:    "By default images are built from....",
	}
	err := survey.AskOne(prompt, &imageRepoExt, survey.Required)
	handleError(err)
	return strings.TrimSpace(imageRepoExt)
}
```

Refactored, see main change (1)
```
func EnterImageRepoExternalRepository() string {
	var imageRepoExt string
	prompt := &survey.Input{
		Message: "Image registry of the form....",
		Help:    "By default images are built from....",
	}
	err := survey.AskOne(prompt, &imageRepoExt, survey.Required)
	handleError(err)
        return HandleResponse(imageRepoExt)     // main change (1)
}

func HandleResponse(value string) string {
        return strings.TrimSpace(value)
}
```
So then we could simply test the HandleResponse method and provide any input value we want. So this could provide sufficient test coverage for that specific prompt.

However, since in interactive mode, in general, we'd like to test the various commands/prompts consecutively.
So potentially, we could take each response and feed it to the subsequent response handler functions to simulate the sequences of prompts during the interactive mode session?

For example, the gitops repo URL will be used to determine the default subfolder name of the output folder.

**Review by bigkevmcd — APPROVED** [review]

**Pull request merged**
