### PR TITLE
Docs: Update docs for Deployment History (#2005)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

**What type of PR is this?**
/kind documentation

**What does this PR do / why we need it**:
Deployment History is added so we should document it. Also the newly added Tabs make the existing screenshots out-of-date.

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

See https://issues.redhat.com/browse/GITOPS-2005

### CODE REVIEW

**Comment by keithchong** [comment]
Hi @reginapizza and @chetan-rns , could you please review this? Thanks.

**Review by chetan-rns — APPROVED** [review]
/lgtm

Thanks @keithchong

**Pull request merged**
