### PR TITLE
Drop custom Argo CD resources

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

/kind code-refactoring

**What does this PR do / why we need it**:

1. Remove the locally maintained Argo CD operand and Application types
2. Use the upstream Argo CD types
3. Upgrade k8s deps

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by ishitasequeira — COMMENTED** [review]
Thanks @chetan-rns for the PR. LGTM!
@wtam2018 can you PTAL?

**Comment by varshab1210** [comment]
Closing this, please feel free to reopen if required

**Pull request closed without merging**
