### PR TITLE
Smart default for bootstrap options except for epic point 5; Fix 147

### LINKED ISSUE #147: kam fails to write resources to output folder 'B' after user is prompted to not overwrite the contents of folder 'A'
**Describe the bug**
kam prompts the user to provide the output folder of the generated resource files.  If that folder already has the generated files from a previous run (includes pipelines.yaml), then the user is prompted to overwrite or change the output path.  If the user chooses another folder (an empty folder for example), then the resources are not generated and no error is reported.

**To Reproduce**
Make sure you already have kam-generated code somewhere in your filesystem. Let's refer to this folder as `A`.
1. Run `kam bootstrap` and follow all questions until you are asked to provide the output path
2. Provide the path for folder `A`
3. You will be prompted to overwrite
4. Select No
5. You will be prompted to provide another path
6. Specify a new path to an empty folder, call this, path `B`
7. Proceed with the rest of the prompts to end.  kam reports everything is ok.
==> Check path `B` and it will still be empty

**Expected behavior**
Path `B` should have the generated files

**Screenshots**
Here is a sample output:
```

kam bootstrap
  
Checking dependencies

 ✓  Checking if Sealed Secrets is installed with the default configuration [347ms]
 ✓  Checking if ArgoCD Operator is installed with the default configuration [567ms]
 ✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [654ms]
  
Starting interactive prompt

? Provide the URL for your GitOps repository https://github.com/keithchong/gitops9.git
? Select type of image registry External Registry
? Image registry of the form <registry>/<username>/<image name> which is used to push newly built images. quay.io/keithchong/taxi
? Path to config.json which authenticates image pushes to the desired image registry /Users/kchong/Downloads/keithchong-robot-auth.json
? Provide a secret (minimum 16 characters) that we can use to authenticate incoming hooks from your Git hosting service for the Service repository. (if not provided, it will be auto-generated) 
? Provide the URL for your Service repository e.g. https://github.com/organisation/service.git https://github.com/keithchong/taxi.git
? Is this repository a private repository? no
? Provide a secret (minimum 16 characters) that we can use to authenticate incoming hooks from your Git hosting service for the Service repository. (if not provided, it will be auto-generated) 
? Do you want to enable commit-status-tracker? yes
? Please provide a token used to authenticate requests to "https://github.com/keithchong/taxi.git" [? for help] ****************************************
? Add a prefix to the environment names(dev, stage, cicd etc.) to distinguish and identify individual environments? 
? Provide a path to write GitOps resources? /Users/kchong/wrh/git/kam/dist
? Do you want to overwrite your output path?  [Use arrows to move, type to filter]
? Do you want to overwrite your output path? no
  
Completing Bootstrap process

 ✓  Authentication tokens encrypted in secrets
 ✓  Pipelines tracker has been configured
 ✓  OpenShift Pipelines resources created
 ✓  Openshift Route for EventListener created
 ✓  Created dev, stage and CICD environments
 ✓  Bootstrapped OpenShift resources successfully

 Next Steps:
 Please refer to https://github.com/redhat-developer/kam/tree/master/docs to get started.
```

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

Have to create another PR. I had an issue with rebase with the original PR: https://github.com/redhat-developer/kam/pull/148.
It's easier just to create a new PR and close the other one.

**What type of PR is this?**
Use this one instead, but see comments from the original PR.
This is for the smart defaulting for kam bootstrap. This also includes a bug fix for #147 , since testing of the feature uncovered the bug.

/kind bug - Fixes 147
/kind enhancement - See GitOps story 563.  Fixes points 1 to 4.

**What does this PR do / why we need it**:
See
GitOps story 563 points 1-4
#147

**Have you updated the necessary documentation?**
(Not yet)

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:
Fixes #147
and GitOps story 563 points 1-4

**How to test changes / Special notes to the reviewer**:
Run kam bootstrap and see if you get prompted for the output folder. Check that the resources are written to the current folder.

### CODE REVIEW

**Review by bigkevmcd — APPROVED** [review]
I'm happy enough with the improvements in this branch.

**Comment by keithchong** [comment]
**Test scenarios.  What was tested during unit testing:**

`kam bootstrap` with any argument EXCEPT `--interactive` should be in non-interactive mode, as before.

`kam bootstrap` launches command into interactive mode, as before

Also `kam bootstrap --interactive` launches command into interactive mode

`kam bootstrap --interactive and WITH one or more flags` launches command into interactive mode.  Any values for flags specified on the command line will be used. The values can override the default values OR if the user chooses to, they can even specify the default value. Interactive mode SHOULD NOT ask for the values of these flags. (In other words, there is no point in prompting the user for a value that was already specified on the command line.)  This fulfills the acceptance criteria of the enhancement.

If in interactive mode, the very first question displayed is to prompt the user to choose to use defaults or not.  Should test for both yes and no responses, and then answer remaining questions until KAM finishes.  Also test that flags from the command line are honoured and not prompted again during interactive mode. Keep in mind what are defaults, and what has been overridden.

**Examples**

`kam bootstrap --interactive`  --> Use defaults? --> No --> This should bring you to the original behaviour as before this enhancement was added.

`kam bootstrap --interactive`  --> Use defaults? --> Yes --> This should prompt you for required flags, and related questions.

`kam bootstrap --service-repo-url https://github.com/keithchong/taxi.git --image-repo quay.io/keithchong/taxi --gitops-repo-url https://github.com/keithchong/gitops11.git --dockercfgjson ~/Downloads/keithchong-robot-auth.json --interactive
should prompt you for your git token

Do test override output folder or not

**Pull request merged**
