### PR TITLE
Providing github.com login instance

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind enhancement

**What does this PR do / why we need it**:
Needed for day 1 operation test automation on openshift CI platform
**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes NA

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by amitkrout** [comment]
blocked due to - https://github.com/openshift/release/pull/13672

**Comment by amitkrout** [comment]
> blocked due to - [openshift/release#13672](https://github.com/openshift/release/pull/13672)

/hold

**Comment by amitkrout** [comment]
Github login secret mount is successful through the test script, however it fails with permission issue while creating the directory. 

```
+ gh auth login --with-token
mkdir /.config: permission denied 
```

The same steps works fine locally.
```
[root@1d87ac4410fb kam]# gh auth login --with-token < secret
[root@1d87ac4410fb kam]# gh auth logout
? Are you sure you want to log out of github.com account 'kam-bot'? Yes
✓ Logged out of github.com account 'kam-bot'
[root@1d87ac4410fb kam]#
```

I will check with ```sudo``` access in the test script.

**Comment by bigkevmcd** [comment]
Have you tried putting the token into the `GH_TOKEN` environment variable?

**Comment by amitkrout** [comment]
> Have you tried putting the token into the `GH_TOKEN` environment variable?

@bigkevmcd yes, i have done it here - https://github.com/openshift/release/blob/master/ci-operator/config/redhat-developer/kam/redhat-developer-kam-master__v4.5.yaml#L42

otherwise it would have thrown error like 
```
# gh auth login --with-token < secret123
bash: secret123: No such file or directory
```

**Comment by bigkevmcd** [comment]
There's some confusion over the token, but this seems to work for me.

```
$ export GITHUB_TOKEN=<redacted>
$ ls -lart ~/.config/gh/hosts.yaml
ls: cannot access '/home/kmcdermo/.config/gh/hosts.yaml': No such file or directory
$ gh pr list
Showing 5 of 5 open pull requests in redhat-developer/kam

#87  Executing kam command scenario                              amitkrout:executingKamCommandScenario
#86  Applying test env variable check                            amitkrout:applyingTestEnvVariableCheck
#85  Providing github.com login instance                         amitkrout:githubLogin
#83  Onboard godog test framework with a basic test              amitkrout:onboardGodogFrameworkWithBasicTest
#82  Adds the prefix to the config map for the gitops-operator.  gaganhegde:config-map-mod
```

**Comment by amitkrout** [comment]
Locally within the test [container](https://github.com/redhat-developer/kam/blob/master/openshift-ci/build-root/Dockerfile) it works for me too.

Now with ```sudo``` permission i am hitting more issues in CI platform 
```
 + sudo gh auth login --with-token
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
sudo: no valid sudoers sources found, quitting
sudo: setresuid() [0, 0, 0] -> [1000780000, -1, -1]: Operation not permitted
sudo: unable to initialize policy plugin
```

Not sure how the same container behaves differently in CI. I will report it in testplatform to get more clarity on this.

**Pull request closed without merging**
