### PR TITLE
fix: add defaults for image repo and pipelines

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

> /kind bug

**What does this PR do / why we need it**:

The `service add` command should generate trigger binding that injects the image repo into the trigger template. This commit adds default pipeline and image repo if they're absent.

Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes https://issues.redhat.com/browse/GITOPS-755

**How to test changes / Special notes to the reviewer**:

1. Create a new env using the env add command
2. Create a new service in the newly added env
3. Add webhook to the new service repo
4. Make a PR to the new service repo and observe if the pipeline is successful

### CODE REVIEW

**Comment by amitkrout** [comment]
@chetan-rns For local verification, you can give a try to write the test automation step in the local.feature file under ```@local``` tag.

**Comment by amitkrout** [comment]
@wtam2018 Are we consuming this change for GA 1.1 ?

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve
@chetan-rns ty!

**Comment by chetan-rns** [comment]
@amitkrout Yeah. Will raise a separate PR for local e2e test

**Pull request merged**
