### PR TITLE
Bump pipelines and trigger version

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**
> /kind code-refactoring

**What does this PR do / why we need it**:
This PR updates the Pipeline and Triggers version used by kam. Updating Pipeline to v0.24.2 and Triggers to v0.14.2. Event listener is the only resource affected by this change 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

**How to test changes / Special notes to the reviewer**:

Day 1 and Day 2 operations are successful on OCP 4.8

### CODE REVIEW

**Comment by ishitasequeira** [comment]
/test v4.8-integration-e2e
Tested on OCP 4.8, works for me. 
/lgtm

**Comment by varshab1210** [comment]
Looks like a flaky - ```Then login argocd API server fails. ```
/retest

**Comment by varshab1210** [comment]
Test platform issue
/retest

**Pull request merged**
