### PR TITLE
Uploading kam bits to prow artifacts

### LINKED ISSUE #38: Upload kam bits to prow artifacts directory
**Is your feature request related to a problem? Please describe.**
Uploading all platform kam bits to prow artifacts directory is to keep the binary that comprises the pr changes and can be shared publicly to test a particular fix.

**Describe the solution you'd like**
All platform bits should be available in prow artifacts directory for each pr

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind feature

**What does this PR do / why we need it**:
All platform bits should be available in prow artifacts directory for each pr

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #38

**How to test changes / Special notes to the reviewer**:

Bits should be available here at - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-developer_kam/39/pull-ci-redhat-developer-kam-master-unit/1310893860162899968/artifacts/unit/

### CODE REVIEW

**Comment by amitkrout** [comment]
Bit are uploaded - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-developer_kam/39/pull-ci-redhat-developer-kam-master-unit/1310893860162899968/artifacts/unit/

**Comment by chetan-rns** [comment]
@wtam2018 approve label is required to trigger the merge

**Review by chetan-rns — APPROVED** [review]

**Comment by amitkrout** [comment]
> @wtam2018 `approved` label is required to trigger the merge

/approve

**Pull request merged**
