### PR TITLE
Install GitOps operator

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind enhancement

**What does this PR do / why we need it**:
Installing OpenShift GitOps operator through test script

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes NA

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by amitkrout** [comment]
```
++ oc get csv -n openshift-operators
+ operator_status='openshift-gitops-operator.v1.0.0             Red Hat OpenShift GitOps               1.0.0                                                  Installing'
+ [[ openshift-gitops-operator.v1.0.0             Red Hat OpenShift GitOps               1.0.0                                                  Installing == *\S\u\c\c\e\e\d\e\d* ]]
++ expr 4 + 1
+ count=5
+ sleep 10
+ '[' 5 -lt 5 ']'
+ echo 'Completed OpenShift GitOps operator installation'
```
Increasing timeout

**Comment by chetan-rns** [comment]
Sorry! Wrong PR
/lgtm cancel

**Comment by amitkrout** [comment]
```
++ oc get csv -n openshift-operators
++ grep openshift-gitops-operator
+ operator_status='openshift-gitops-operator.v1.0.0             Red Hat OpenShift GitOps               1.0.0                                                  Installing'
+ [[ openshift-gitops-operator.v1.0.0             Red Hat OpenShift GitOps               1.0.0                                                  Installing == *\S\u\c\c\e\e\d\e\d* ]]
++ expr 2 + 1
+ count=3
+ sleep 10
+ '[' 3 -lt 15 ']'
++ oc get csv -n openshift-operators
++ grep openshift-gitops-operator
+ operator_status='openshift-gitops-operator.v1.0.0             Red Hat OpenShift GitOps               1.0.0                                                  Succeeded'
+ [[ openshift-gitops-operator.v1.0.0             Red Hat OpenShift GitOps               1.0.0                                                  Succeeded == *\S\u\c\c\e\e\d\e\d* ]]
+ break
+ echo 'Completed OpenShift GitOps operator installation'
```
Gitops operator installation succeeded

Details log - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-developer_kam/171/pull-ci-redhat-developer-kam-master-v4.6-integration-e2e/1361955981180801024/artifacts/integration-e2e/integration-e2e-steps/build-log.txt

**Review by chetan-rns — APPROVED** [review]

**Review by chetan-rns — APPROVED** [review]
Thank you!

**Pull request merged**
