### PR TITLE
[GITOPS-750] Hide Commit Status Tracker

### PR DESCRIPTION
**Pull request by iam-veeramalla**
> /kind code-refactoring

PR https://github.com/redhat-developer/kam/pull/203 feels incomplete without this change. 

> Commit status tracker is an experiential project hosted in Tekton.  Tekton will support this feature out of the box in future release.   The current status of commit status tracker is not stable as it has not been kept up-to-date with Tekton APIs changes.   We should hide user visible option to enable commit status tracker for the time being until we switch over to use the native support in Tekton (ref to ticket).

**How to test changes / Special notes to the reviewer**:
1. Verify that Commit Status Tracker flag is hidden from bootstrap options and not enabled by default. 
2. Create a commit to either SERVICE REPO or GITOPS REPO , It can be as small as editing a README.md file. Make sure that Pipelines are run on Openshift UI(CICD namespace)
3.  Verify that status of the Pipelines(Success or Failure) is not reflected on commit or PR.

### CODE REVIEW

**Comment by chetan-rns** [comment]
Thanks for the PR @iam-veeramalla, tested locally and the commit status tracker resources were not generated. We should also remove the commit status tracker annotations that are added to the `PipelineRuns` in [ci-dryrun-from-push-template](https://github.com/chetan-rns/gitops/blob/1efe916b02790cc64ef5da3c6160af547465cecc/config/cicd/base/07-templates/ci-dryrun-from-push-template.yaml#L20) and [app-ci-template](https://github.com/chetan-rns/gitops/blob/1efe916b02790cc64ef5da3c6160af547465cecc/config/cicd/base/07-templates/app-ci-build-from-push-template.yaml#L33).

**Comment by chetan-rns** [comment]
https://github.com/redhat-developer/kam/blob/3619aa51941f6801ab969f2046d2ab5366281fb7/pkg/cmd/bootstrap.go#L418

Small nit. Can we remove the reference to the status tracker in the flag description?
> , and commit-status notifications (if enabled)

**Comment by iam-veeramalla** [comment]
> Thanks for the PR @iam-veeramalla, tested locally and the commit status tracker resources were not generated. We should also remove the commit status tracker annotations that are added to the `PipelineRuns` in [ci-dryrun-from-push-template](https://github.com/chetan-rns/gitops/blob/1efe916b02790cc64ef5da3c6160af547465cecc/config/cicd/base/07-templates/ci-dryrun-from-push-template.yaml#L20) and [app-ci-template](https://github.com/chetan-rns/gitops/blob/1efe916b02790cc64ef5da3c6160af547465cecc/config/cicd/base/07-templates/app-ci-build-from-push-template.yaml#L33).

Made the required changes. Can you please review again :)

**Comment by wtam2018** [comment]
Reminder:  We are in code freeze.

**Review by chetan-rns — APPROVED** [review]
Screenshot from 2021-03-26 12-03-25
Pipelines are successfull
/lgtm

**Pull request merged**
