### PR TITLE
Update to OS Pipelines 1.10 and k8s dependencies (#2337)

### PR DESCRIPTION
**Pull request by keithchong**
**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #? 

See Jira https://issues.redhat.com/browse/GITOPS-2337
Documentation has not been updated.  Code changes only for now.

**How to test changes / Special notes to the reviewer**:
Untested PR. MUST test with pipelines feature with kam after bootstrapping steps (Do day 1 and 2 operations)

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
Hi @keithchong , Thanks for the PR.
@chetan-rns will be able to review this PR ?

**Review by chetan-rns — APPROVED** [review]
Thanks @keithchong 

/lgtm

**Comment by keithchong** [comment]
The go version that is being used is 1.16 and I think we need 1.18

go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/go/.cache"
GOENV="/alabama/.config/go/env"
GOEXE=""
GOFLAGS="-mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.12"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/src/github.com/redhat-developer/kam/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2469114545=/tmp/go-build -gno-record-gcc-switches"

**Comment by wtam2018** [comment]
Oh yeah. @varshab1210 The OpenShift CI needs to upgrade go.

**Comment by keithchong** [comment]
The original error message isn't quite useful:

_error: failed to execute wrapped command: exit status 2_

I believe the underlying error message is:

go.mod file indicates go 1.18, but maximum supported version is 1.16

**Comment by varshab1210** [comment]
> The original error message isn't quite useful:
> 
> _error: failed to execute wrapped command: exit status 2_
> 
> I believe the underlying error message is:
> 
> go.mod file indicates go 1.18, but maximum supported version is 1.16

Thanks @keithchong, good catch. I will raise a PR

**Pull request merged**
