### PR TITLE
Update operator subscription channel

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**

/kind failing-test
/kind enhancement

**What does this PR do / why we need it**:
Fix of - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/237/pull-ci-redhat-developer-kam-master-v4.7-integration-e2e/1392449843313512448#1:build-log.txt%3A371

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes of https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_kam/237/pull-ci-redhat-developer-kam-master-v4.7-integration-e2e/1392449843313512448#1:build-log.txt%3A371

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by amitkrout** [comment]
This change installs gitops operator 1.1.0

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
