### PR TITLE
CI:Updating golang version to 1.18

### PR DESCRIPTION
**Pull request by varshab1210**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by chetan-rns** [comment]
@varshab1210 Could you also update the version in the README?

https://github.com/redhat-developer/kam#how-to-contribute

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
