### PR TITLE
chore: upgrade go version

### PR DESCRIPTION
**Pull request by rishabh625**
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

/kind chore

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:
upgrades go version
Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by chetan-rns — APPROVED** [review]
/lgtm
/approve

**Comment by rishabh625** [comment]
need to update k8s library as separate PR as it requires updation to below libraries too.
vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go:117:11: cannot use spec.Schema{…} (value of type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in struct literal
vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go:146:20: cannot use ref("k8s.io/api/core/v1.Toleration") (value of type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in struct literal

**Pull request merged**
