### PR TITLE
WIP Get tests running

### PR DESCRIPTION
**Pull request by bigkevmcd**
**What type of PR is this?**

Work in progress...

/kind failing-test

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by wtam2018** [comment]
Ironically both reviewers are no longer with the company.   I will fix the OWNERS file.

**Comment by bigkevmcd** [comment]
> Ironically both reviewers are no longer with the company. I will fix the OWNERS file.

I'm not necessarily going to actually get this landed, I created it to trigger the e2e tests to try and debug the issues we're seeing, and I think I know what's going on...and it's not pretty :-)

https://github.com/openssh/openssh-portable/blob/master/misc.c#L1105 looks like the offending code

**Pull request closed without merging**
